### PR TITLE
Prevent pairings from including players twice

### LINKED ISSUE #124: [Bug]: Player can be pair against themself
## What went wrong:
When submitting players for the `CreateRound` tournament operation, a player can play against themself and the tournament does not return an error.

## Expected behavior:
This should not happen. Operations like this should return an error by checking that no players are repeated.

### PR DESCRIPTION
**Pull request by zbrachinara**
fixes #124

### CODE REVIEW

File: squire_lib/src/tournament.rs [hunk 1]
```diff
@@ -1269,6 +1273,62 @@ mod tests {
             .assume_pair();
     }
 
+    #[test]
+    fn create_round_test() {
+        let mut tourn =
+            Tournament::from_preset("Test".into(), TournamentPreset::Swiss, "Test".into());
```
Comment (TylerBloom) [inline squire_lib/src/tournament.rs:1279]: There should be a method in `squire_tests` to get a "default" seed.

File: squire_lib/src/tournament.rs [hunk 2]
```diff
@@ -1269,6 +1273,62 @@ mod tests {
...
+            .take(2)
+            .collect_vec();
+        let repeated_players = std::iter::repeat(make_player(&mut tourn))
+            .take(2)
+            .collect_vec();
+
+        assert!(tourn.start().is_ok());
+
+        assert_eq!(
+            tourn.create_round(default_salt, players_too_large),
```
Comment (TylerBloom) [inline squire_lib/src/tournament.rs:1305]: Nit: Its generally easier to use `Utc::now()`:
```suggestion
            tourn.create_round(Utc::now(), players_too_large),
```

**Review by TylerBloom — DISMISSED** [review]
Overall, looks good. Just a couple of minor nitpicks with the tests.

File: squire_lib/src/tournament.rs (hunk 1 above)
Comment (zbrachinara) [reply squire_lib/src/tournament.rs:1279]: This can't be used directly from a unit test in `squire_lib`. I think it's trying to compile `squire_lib` twice -- so that it can compile `squire_tests` as a dev-dependency, and the crate itself with `cfg(test)` -- and so it ends up with two different versions of the `TournamentSeed` struct. The seed can't be used destructured either, because the `TournamentPreset` type isn't standard, so it can't be used from outside `squire_tests`. It could work if you re-export all the types used in `squire_tests`, but I'm not sure if that's necessary.

Comment (TylerBloom) [reply squire_lib/src/tournament.rs:1279]: Ah, ya. That is a problem. That would create a circular dependency. But, we don't need to access any private fields/methods for this test, so it should probably be an integration test anyway. Any calls to `create_round` should be replaced with create round tournament operations.

**Review by TylerBloom — APPROVED** [review]
